version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: quiz_db_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: quiz_adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    dbdata: