version: '3.1'

services:
    db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_DATABASE: quiz
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: 12345678
        MYSQL_ROOT_PASSWORD: 12345678
      volumes:
        - dbdata:/var/lib/mysql
        - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
      
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

volumes:
    dbdata:

services:

  db:
    image: mysql

  